### ISSUE TITLE
Glitches 

### ISSUE THREAD

**Issue by rajanarahul93** [vicky2005-21/Crypto-Web#1]
@vicky2005-21   there are some glitches in the above given website i.e
1)In the crypto tab , currency changing option it is giving error
2)By clicking on only name shows the results or information regarding it 
By my side I think that should be changed like clicking on any place in the tab of the particular crypto should give the information

**Comment by Animesh239** [comment]
the first problem is not a glitch , you have to enter a valid currency code ( INR for indian rupee, CNY for chinese yuan) and then click on the submit icon.

**Comment by vicky2005-21** [comment]
Its developed. Thanks for noticing.
